trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'TF-deployment'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Install Terraform
        curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/

        export ARM_CLIENT_ID=$AZURE_CLIENT_ID
        export ARM_CLIENT_SECRET=$AZURE_CLIENT_SECRET
        export ARM_SUBSCRIPTION_ID=$AZURE_SUBSCRIPTION_ID
        export ARM_TENANT_ID=$AZURE_TENANT_ID

        # Initialize Terraform
        terraform init

        # Plan Terraform deployment
        terraform plan -out tfplan

        # Apply Terraform deployment
        terraform apply -auto-approve tfplan
