trigger:
- main

variables:
  terraformVersion: '1.4.6'
  azureServiceConnection: 'Test-22'

stages:
- stage: Terraform
  jobs:
  - job: Terraform
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: '<your_resource_group>'
        backendAzureRmStorageAccountName: '<your_storage_account>'
        backendAzureRmContainerName: '<your_container>'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: $(azureServiceConnection)
        commandOptions: '-out=tfplan'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        environmentServiceNameAzureRM: $(azureServiceConnection)
        commandOptions: '-auto-approve tfplan'
